pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/OlenaSakhanda1/dqe-automation.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''#!/bin/bash
set -e
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r PyTest\\ DQ\\ Framework/requirements.txt
pip install PyYAML pytest-html
'''
            }
        }

        stage('List Parquet Data in Repo Folder') {
            steps {
                sh '''
echo "📂 parquet_output content:"
ls -la "PyTest DQ Framework/src/connectors/file_system/parquet_output" || echo "No parquet data found"
cd "PyTest DQ Framework/src/connectors/file_system/parquet_output"
find .
'''
            }
        }

        stage('Run Pytest') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-postgres-credentials', usernameVariable: 'POSTGRES_SECRET_USR', passwordVariable: 'POSTGRES_SECRET_PSW')]) {
                    sh '''#!/bin/bash
set -e
source venv/bin/activate
mkdir -p html_report
export POSTGRES_SECRET_USR=$POSTGRES_SECRET_USR
export POSTGRES_SECRET_PSW=$POSTGRES_SECRET_PSW

pytest PyTest\\ DQ\\ Framework/tests -m "parquet_data" \
    --db_host="postgres" \
    --db_port="5432" \
    --db_name="mydatabase" \
    --db_user=$POSTGRES_SECRET_USR \
    --db_password=$POSTGRES_SECRET_PSW \
    --html=html_report/report.html \
    --self-contained-html \
    --capture=tee-sys
'''
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true
                archiveArtifacts artifacts:
 'PyTest DQ Framework/src/connectors/file_system/parquet_output/**', allowEmptyArchive: true
                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'html_report',
                    reportFiles: 'report1.html',
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }
}

