pipeline {
    agent any
    stages {
        stage('Update Packages') {
            steps {
                script {
                    sh 'apt-get update'
                    sh 'apt-get install -y libpq-dev'
                }
            }
        }
        stage('Install Python') {
            steps {
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }
        stage('Clone Repository') {
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/DanyaHDanny/dqe-automation'
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r data_dev/requirements.txt
                    '''
                }
            }
        }
        stage('Run main') {
            steps {
                script {
                    sh '''
                        . venv/bin/activate
                        export PYTHONPATH=$WORKSPACE
                        python data_dev/main.py
                    '''
                }
            }
        }
        stage('List Parquet Data') {
            steps {
                sh 'ls -la /parquet_data || echo "No parquet data found"'
            }
        }
        stage('Prepare Shared Parquet Folder') {
            steps {
                sh 'mkdir -p /var/jenkins_home/shared_parquet'
            }
        }
        stage('Copy Parquet Data to Shared Folder') {
            steps {
                sh '''
                    cp -r /parquet_data/* /var/jenkins_home/shared_parquet/
                    echo "✅ Parquet data copied to shared folder:"
                    ls -la /var/jenkins_home/shared_parquet || echo "No parquet data found"
                '''
            }
        }
        stage('Archive Parquet Artifacts') {
            steps {
                archiveArtifacts artifacts: '/var/jenkins_home/shared_parquet/**', allowEmptyArchive: true
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}
